{
    'name': "Payment Request",
    'summary': "Payment Request",
    'author': "Oksana Yeroshenko",
    'website': "https://odoo-pro.com.ua/",
    'category': 'Finance',
    'version': '18.0.0.1.0',
    'depends': ['account', 'portal', 'hr'],
    'data': [
        'data/ir_sequence.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'views/payment_request_views.xml',
        'wizard/payment_request_create_bill_wizard_views.xml',
        'views/res_users_views.xml',
        'views/portal_templates.xml',
        'views/account_vendor_bills_to_check_menu.xml',
        'views/account_move_views.xml',
    ],
    'application': True,
    'installable': True,
    'sequence': -100,
    'license': 'LGPL-3',
}
